# Generated by Django 4.0.1 on 2022-02-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_height_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inspection_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='receipt_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
