# Generated by Django 4.0.1 on 2022-02-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename__id_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='_id',
        ),
    ]
